# Generated by Django 5.1 on 2024-12-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nowlogin',
            name='user',
        ),
        migrations.AddField(
            model_name='nowlogin',
            name='login',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
