# Generated by Django 5.1 on 2024-12-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_nowlogin_user_nowlogin_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='nowlogin',
            name='ip',
            field=models.GenericIPAddressField(default=''),
        ),
    ]
