# Generated by Django 5.1 on 2024-12-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_nowlogin_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowlogin',
            name='ip',
            field=models.GenericIPAddressField(default='0'),
        ),
    ]
