# Generated by Django 5.1 on 2024-12-13 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_nowlogin_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='nowlogin',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='nowlogin',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
